version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - forms-service
      - auth-service
      - frontend
    networks:
      - ${APP_NETWORK}

  forms-service:
    build: ./forms-service
    expose:
      - "${FORMS_SERVICE_PORT}"
    environment:
      - PORT=${FORMS_SERVICE_PORT}
      - DATABASE_URL=postgresql://${FORMS_DB_USER}:${FORMS_DB_PASSWORD}@${FORMS_DB_HOST}:${FORMS_DB_PORT}/${FORMS_DB_NAME}
    depends_on:
      db_forms:
        condition: service_healthy
    networks:
      - ${APP_NETWORK}

  db_forms:
    image: postgres:13
    environment:
      POSTGRES_USER: ${FORMS_DB_USER}
      POSTGRES_PASSWORD: ${FORMS_DB_PASSWORD}
      POSTGRES_DB: ${FORMS_DB_NAME}
    volumes:
      - postgres_forms_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${FORMS_DB_USER} -d ${FORMS_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ${APP_NETWORK}

  auth-service:
    build: ./auth-service
    expose:
      - "${AUTH_SERVICE_PORT}"
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - DATABASE_URL=postgresql://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
    depends_on:
      db_auth:
        condition: service_healthy
    networks:
      - ${APP_NETWORK}

  db_auth:
    image: postgres:13
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ${APP_NETWORK}

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - ${APP_NETWORK}

volumes:
  postgres_forms_data:
  postgres_auth_data:

networks:
  app-network:
    driver: bridge