apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-auth
spec:
  serviceName: "db-auth"
  replicas: 1
  selector:
    matchLabels:
      app: db-auth
  template:
    metadata:
      labels:
        app: db-auth
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "auth_db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-auth-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-auth-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db-auth
spec:
  ports:
  - port: 5432
  selector:
    app: db-auth