name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  FRONTEND_IMAGE: survey-app-frontend
  AUTH_SERVICE_IMAGE: survey-app-auth-service
  FORMS_SERVICE_IMAGE: survey-app-forms-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version tag
        id: vars
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE:${{ steps.vars.outputs.VERSION }} ./frontend
          docker push $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE:${{ steps.vars.outputs.VERSION }}
          docker tag $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE:${{ steps.vars.outputs.VERSION }} $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE:latest
          docker push $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE:latest

      - name: Build and push auth-service
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE:${{ steps.vars.outputs.VERSION }} ./auth-service
          docker push $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE:${{ steps.vars.outputs.VERSION }}
          docker tag $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE:${{ steps.vars.outputs.VERSION }} $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE:latest
          docker push $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE:latest

      - name: Build and push forms-service
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE:${{ steps.vars.outputs.VERSION }} ./forms-service
          docker push $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE:${{ steps.vars.outputs.VERSION }}
          docker tag $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE:${{ steps.vars.outputs.VERSION }} $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE:latest
          docker push $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE:latest