name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

permissions:
  contents: write

env:
  DOCKER_HUB_USERNAME: matveysviadysh
  FRONTEND_IMAGE: survey-app-frontend
  AUTH_SERVICE_IMAGE: survey-app-auth-service
  FORMS_SERVICE_IMAGE: survey-app-forms-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }} ./frontend
          docker push $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }}

      - name: Build and push auth-service
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }} ./auth-service
          docker push $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }}

      - name: Build and push forms-service
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }} ./forms-service
          docker push $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }}

      - name: Update deployment files
        run: |
          sed -i "s|image: $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE.*|image: $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }}|g" docker-compose.prod.yml
          sed -i "s|image: $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE.*|image: $DOCKER_HUB_USERNAME/$AUTH_SERVICE_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }}|g" docker-compose.prod.yml
          sed -i "s|image: $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE.*|image: $DOCKER_HUB_USERNAME/$FORMS_SERVICE_IMAGE:${{ steps.vars.outputs.COMMIT_SHA }}|g" docker-compose.prod.yml
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docker-compose.prod.yml
          git commit -m "Update to version ${{ steps.vars.outputs.COMMIT_SHA }}"
          git push

  